[target.'cfg(target_family = "wasm")']
rustflags = ["--cfg=web_sys_unstable_apis", "--cfg=getrandom_backend=\"wasm_js\""]

# Enable for testing WASM-only stuff
[build]
#target = "wasm32-unknown-unknown"
